# Generated by Django 3.2.9 on 2022-01-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_cita_cita_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=b'I01\n')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=b'I01\n')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.user')),
                ('user_who_like', models.ManyToManyField(related_name='likes', to='app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
