# Generated by Django 3.2.9 on 2022-05-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220116_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user_who_like',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
